name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  close-pull-request:
    runs-on: ubuntu-20.04
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "It is mirror from: https://gitlab.com/phnx47/pkg-update"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}